# Generated by Django 3.0.3 on 2020-06-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmessage',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='message',
        ),
    ]
