# Generated by Django 3.0.3 on 2020-06-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_contacts_emaillist_phonelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='OrgContact',
        ),
    ]
