# Generated by Django 3.0.3 on 2020-06-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20200615_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcontact',
            name='fb_group_link',
            field=models.URLField(max_length=1000),
        ),
    ]
