# Generated by Django 3.0.3 on 2020-06-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='o+', max_length=4)),
                ('birth_date', models.DateField()),
                ('present_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blood_donor_status', models.BooleanField(default=True, help_text='Ready Now?', verbose_name='Is Physical Condition Good ?')),
            ],
            options={
                'verbose_name': 'Donor List',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_or_birthday_no', models.CharField(blank=True, help_text='Add your NID number or Birthday Number', max_length=100, null=True)),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('educational_status', models.CharField(help_text='S.S.C or H.S.C or B.S.C', max_length=250)),
                ('occupation', models.CharField(help_text='Student/Business/Farmer/..', max_length=250)),
                ('relegion', models.CharField(choices=[('i', 'Islam'), ('h', 'Hindu'), ('k', 'Khristan'), ('o', 'Others')], default='i', max_length=1)),
                ('facebook_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/member/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_member', to='donor.Donor', verbose_name='Related Donor Info')),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('patient_type', models.CharField(blank=True, help_text='Operation', max_length=255, null=True)),
                ('hospital_name', models.CharField(blank=True, help_text='Osmani Medical College', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donation_details', to='donor.Donor')),
            ],
            options={
                'ordering': ['created_date', 'updated_date'],
            },
        ),
    ]
