# Generated by Django 3.0.3 on 2020-06-22 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='o+', max_length=4)),
                ('birth_date', models.DateField()),
                ('present_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blood_donor_status', models.BooleanField(default=True, help_text='Your health is good?', verbose_name='Health Good')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor List',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgMemorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='images/memories/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_or_birthday_no', models.CharField(blank=True, help_text='Add your NID number or Birthday Number', max_length=100, null=True)),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('educational_status', models.CharField(help_text='S.S.C or H.S.C or B.S.C', max_length=250)),
                ('occupation', models.CharField(help_text='Student / Business / Farmer /..', max_length=250)),
                ('relegion', models.CharField(choices=[('i', 'Islam'), ('h', 'Hindu'), ('k', 'Khristan'), ('o', 'Others')], default='i', max_length=1)),
                ('running_position_status', models.CharField(choices=[('running', 'Running'), ('retired', 'Retired')], default='running', max_length=10)),
                ('facebook_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('position_name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/member/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '400x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_member', to='donor.Donor', verbose_name='Related Donor Info')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalOrgMemorie',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.TextField(max_length=100)),
                ('cropping', image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical org memorie',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMember',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nid_or_birthday_no', models.CharField(blank=True, help_text='Add your NID number or Birthday Number', max_length=100, null=True)),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('educational_status', models.CharField(help_text='S.S.C or H.S.C or B.S.C', max_length=250)),
                ('occupation', models.CharField(help_text='Student / Business / Farmer /..', max_length=250)),
                ('relegion', models.CharField(choices=[('i', 'Islam'), ('h', 'Hindu'), ('k', 'Khristan'), ('o', 'Others')], default='i', max_length=1)),
                ('running_position_status', models.CharField(choices=[('running', 'Running'), ('retired', 'Retired')], default='running', max_length=10)),
                ('facebook_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('position_name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('cropping', image_cropping.fields.ImageRatioField('image', '400x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='donor.Donor', verbose_name='Related Donor Info')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical member',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDonor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='o+', max_length=4)),
                ('birth_date', models.DateField()),
                ('present_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('blood_donor_status', models.BooleanField(default=True, help_text='Your health is good?', verbose_name='Health Good')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Donor List',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('patient_type', models.CharField(blank=True, help_text='Operation', max_length=255, null=True)),
                ('hospital_name', models.CharField(blank=True, help_text='Osmani Medical College', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donation_details', to='donor.Donor')),
            ],
            options={
                'ordering': ['created_date', 'updated_date'],
            },
        ),
    ]
