# Generated by Django 3.0.3 on 2020-06-29 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='image',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/member/'),
            preserve_default=False,
        ),
    ]
