# Generated by Django 3.0.3 on 2020-06-10 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_donor_status',
            field=models.BooleanField(default=True, help_text='Your health is good?', verbose_name='Health Good'),
        ),
        migrations.AlterField(
            model_name='historicaldonor',
            name='blood_donor_status',
            field=models.BooleanField(default=True, help_text='Your health is good?', verbose_name='Health Good'),
        ),
    ]
