# Generated by Django 3.0.3 on 2020-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['name', 'blood_group']},
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='o+', max_length=4),
        ),
    ]
