# Generated by Django 3.0.3 on 2020-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20200629_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='position_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='position_name',
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='org_position',
            field=models.CharField(choices=[('member', 'সদস্য'), ('permanent_member', 'স্থায়ী কমিটির সদস্য'), ('chairmen', 'সভাপতি'), ('vice_chairmen', 'সহ-সভাপতি'), ('senior_vice_chairmen', 'সিনিয়র সহ-সভাপতি'), ('general_secretary', 'সাধারণ সম্পাদক'), ('organizational_secretary', 'সাংগঠনিক সম্পাদক'), ('finance_secretary', 'অর্থ সম্পাদক'), ('EducationAndSocialWelfareSecretary', 'শিক্ষা ও সমাজ কল্যাণ সম্পাদক'), ('religion_secretary', 'ধর্ম সম্পাদক'), ('InformationAndPlanningSecretary', 'তথ্য ও পরিকল্পনা সম্পাদক'), ('finance_secretary', 'অর্থ সম্পাদক'), ('office_secretary', 'অফিস সম্পাদক'), ('BloodCoordinator', 'ব্লাড সমন্বয়ক'), ('executive_member', 'নির্বাহী সদস্য'), ('HealthSecretary', 'স্বাস্থ্য সম্পাদক'), ('Co-GeneralSecretary', 'সহ-সাধারন সম্পাদক'), ('Co-OrganizingSecretary', 'সহ-সাংগঠনিক সম্পাদক'), ('MemberSecretary', 'সদস্য সচিব'), ('international_secretary', 'আন্তর্জাতিক সম্পাদক')], default='member', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='org_position',
            field=models.CharField(choices=[('member', 'সদস্য'), ('permanent_member', 'স্থায়ী কমিটির সদস্য'), ('chairmen', 'সভাপতি'), ('vice_chairmen', 'সহ-সভাপতি'), ('senior_vice_chairmen', 'সিনিয়র সহ-সভাপতি'), ('general_secretary', 'সাধারণ সম্পাদক'), ('organizational_secretary', 'সাংগঠনিক সম্পাদক'), ('finance_secretary', 'অর্থ সম্পাদক'), ('EducationAndSocialWelfareSecretary', 'শিক্ষা ও সমাজ কল্যাণ সম্পাদক'), ('religion_secretary', 'ধর্ম সম্পাদক'), ('InformationAndPlanningSecretary', 'তথ্য ও পরিকল্পনা সম্পাদক'), ('finance_secretary', 'অর্থ সম্পাদক'), ('office_secretary', 'অফিস সম্পাদক'), ('BloodCoordinator', 'ব্লাড সমন্বয়ক'), ('executive_member', 'নির্বাহী সদস্য'), ('HealthSecretary', 'স্বাস্থ্য সম্পাদক'), ('Co-GeneralSecretary', 'সহ-সাধারন সম্পাদক'), ('Co-OrganizingSecretary', 'সহ-সাংগঠনিক সম্পাদক'), ('MemberSecretary', 'সদস্য সচিব'), ('international_secretary', 'আন্তর্জাতিক সম্পাদক')], default='member', max_length=100),
        ),
    ]
