# Generated by Django 3.0.3 on 2020-06-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20200606_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_donor_status',
            field=models.BooleanField(default=True, help_text='Ready Now?'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.BooleanField(default=False, help_text='Are you agree to donate?'),
        ),
    ]
