# Generated by Django 3.0.3 on 2020-06-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20200629_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmember',
            old_name='org_position',
            new_name='organisation_position',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='org_position',
            new_name='organisation_position',
        ),
    ]
