# Generated by Django 3.0.3 on 2020-06-12 16:50

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20200612_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmember',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '130x130', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '130x130', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
