# Generated by Django 3.0.3 on 2020-06-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20200607_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='Osmani Medical College', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Operation', max_length=255, null=True),
        ),
    ]
