# Generated by Django 3.0.3 on 2020-06-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20200607_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blooddonation',
            options={'ordering': ['-donation_date']},
        ),
        migrations.RenameField(
            model_name='blooddonation',
            old_name='dontation_date',
            new_name='donation_date',
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donation_details', to='donor.Donor'),
        ),
    ]
