# Generated by Django 3.0.3 on 2020-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20200607_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_donor_status',
            field=models.BooleanField(default=True, help_text='Ready Now?', verbose_name='Is Physical Condition Good ?'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1),
        ),
    ]
